### ISSUE TITLE
Template tracking feature

### ISSUE THREAD

**Issue by thomlucc** [BabylonJS/BabylonAR#7]
Status: 
Repeated interest (but no action) shown from FlipGrid, waiting for more tangible signs of interest before further investment.
Multiple demos of technology working at usable framerates, even for low-end devices. Consumption layer prototyped, but no real architecture yet proposed.

Remaining work:

- [x] Rehydrate old demo code and add WASM to Babylon CV.
- [x] Propose and create Babylon CV consumption layer. 
- [x] Profile usage and evaluate need/ways to run faster
**-> Waiting from feedback from Flipgrid on the min perf requirement to able to reach a big enough # of devices**
